name: Backport

on:
  workflow_call:

jobs:
  branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.backport_branches.outputs.result }}
    steps:
      - name: Check for backport labels
        id: backport_branches
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labels = issue.labels.map(label => label.name);
            console.log(`Labels: ${labels}`);

            const branches = labels.filter(label => label.startsWith('backport '))
              .map(label => label.substr(9));
            console.log(`Branches: ${branches}`);

            return branches

  backport:
    runs-on: ubuntu-latest
    needs: branches
    if: ${{ needs.branches.outputs.branches != '[]' && needs.branches.outputs.branches != '' }}
    strategy:
      matrix:
        branch: ${{ fromJson(needs.branches.outputs.branches) }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.TRUSTIFICATION_BOT_ID }}
          application_private_key: ${{ secrets.TRUSTIFICATION_BOT_KEY }}

      - name: Backport
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          pull_title: '${pull_title} [Backport ${target_branch}]'
